baseURL = "https://risk.github.io/"
languageCode = "en-us"
title = "Your Name | Cyber @ Carleton"
theme = "terminal"

[params]
  # The theme comes with a few colors: orange, blue, red, green, pink
  themeColor = "green"
  contentTypeName = "posts"

[params.terminal]
  showDescription = true
  showTitle = true
  userName = "carleton_student"
  textBeforeCursor = "guest@cyber_portfolio:~$"